# Generated by Django 2.0.3 on 2018-03-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ichiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('projection', models.CharField(choices=[('steamer', 'STEAMER'), ('the-bat', 'The Bat')], max_length=500)),
                ('ab', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='scrape',
            options={'get_latest_by': 'datetime', 'ordering': ('-datetime',)},
        ),
    ]
