# Generated by Django 2.0.3 on 2018-04-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ichiro', '0003_auto_20180331_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='projection',
            field=models.CharField(choices=[('steamer-update', 'STEAMER (Update)'), ('the-bat-ros', 'The Bat (RoS)'), ('the-bat-adjusted-ros', 'The Bat (Adjusted RoS)'), ('zips', 'ZiPS (Update)'), ('depth-charts-ros', 'Depth Charts (RoS)'), ('depth-charts-adjusted-ros', 'Depth Charts (Adjusted RoS)')], max_length=500),
        ),
    ]
